name: CI

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v2 
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm run install
      - run: npm run pm2

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/node-app
          remote_host: ${{ secrets.HOST_DNS }}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: npm run build
