name: CI

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 

      - name: Upload Private Key
        uses: actions/upload-artifact@v2
        with:
          name: private-key
          path: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Build & Deploy
        env:
            HOSTDNS: ${{ secrets.HOST_DNS }}

        run: |
          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/private-key ubuntu@${HOSTDNS} '
              cd /home/ubuntu/node-app &&
              git checkout main &&
              git fetch --all &&
              git pull origin main &&
              sudo npm i &&
              sudo npm run pm2 &&
              sudo npm run build
              '

