name: CI

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTDNS: ${{secrets.HOST_DNS}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$HOSTDNS '

              cd /home/ubuntu/node-app &&
              git checkout main &&
              git fetch --all &&
              git pull origin main &&
              sudo npm i &&
              sudo npm run pm2 &&
              sudo npm run build
              '

